spring:
  application:
    name: ${APP_NAME:spring-boot-debug}

server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

logging:
  level:
    org:
      springframework: ${LOG_LEVEL_SPRING:error}
    com:
      luafanti: ${LOG_LEVEL_SERVICE:warn}