name: Build and Push to Docker Hub

on:
  push:
    branches:
      - master
      - develop
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.event.repository.name }}
      IMAGE_TAG: ${{ github.sha }}
      DOCKERHUB_USER: bodax

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set release version from ref
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t $DOCKERHUB_USER/$IMAGE_NAME:$IMAGE_TAG \
            -f ./infra/docker/Dockerfile \
            --label "git.commit=${{ github.sha }}" \
            --label "git.tag=${{ env.RELEASE_VERSION }}" \
            .

      - name: Tag and push image for branch
        if: startsWith(github.ref, 'refs/heads/')
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          docker tag $DOCKERHUB_USER/$IMAGE_NAME:$IMAGE_TAG $DOCKERHUB_USER/$IMAGE_NAME:$BRANCH_NAME
          docker push $DOCKERHUB_USER/$IMAGE_NAME:$BRANCH_NAME

      - name: Tag and push image for version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker tag $DOCKERHUB_USER/$IMAGE_NAME:$IMAGE_TAG $DOCKERHUB_USER/$IMAGE_NAME:${{ env.RELEASE_VERSION }}
          docker push $DOCKERHUB_USER/$IMAGE_NAME:${{ env.RELEASE_VERSION }}
